name: tflite_dart
description: A library for interact with tensorflow lite on cross platform.
version: 0.0.0 
homepage: https://github.com/azkadev/youtube_dart/wiki
repository: https://github.com/azkadev/youtube_dart/
issue_tracker: https://github.com/azkadev/youtube_dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
   ffi: ^2.0.1
   path: ^1.8.0
   quiver: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
